Issue 0091
OpenSmock/Pyramid pull request #120
Opened 2023-11-29 15:19 UTC by Nyan11

https://github.com/OpenSmock/Pyramid/issues/91

2023-11-29 15:37 UTC, Nyan11 commented
The CI is fix here : https://github.com/OpenSmock/Bloc-Serialization/pull/11

2023-12-02 11:38 UTC, labordep reviewed
I don't understand why "roots" have an "s" and why there is a collection and not just BlSpace>>root element when there is no selection.

![image](https://github.com/OpenSmock/Pyramid/assets/49183340/928fa50c-7e1e-4b19-960a-57cf77ece7ff)

2023-12-09 09:31 UTC, Nyan11 commented
> I don't understand why "roots" have an "s" and why there is a collection and not just BlSpace>>root element when there is no selection.
> 

Hello,

I choose "root" to be the collection containing the BlElement.

It was a requirement that Pyramid saves a Collection of elements.
 
If we make it able to edit the `BlSpace>>root element`, i'm afraid we could have unwanted behaviour with the openFromSpace shortcut.

Is the `BlSpace>>root element` the same in Pyramid and in the Space we opened it from ?

2023-12-09 18:13 UTC, labordep commented
> > I don't understand why "roots" have an "s" and why there is a collection and not just BlSpace>>root element when there is no selection.
> 
> Hello,
> 
> I choose "root" to be the collection containing the BlElement.
> 
> It was a requirement that Pyramid saves a Collection of elements.
> 
> If we make it able to edit the `BlSpace>>root element`, i'm afraid we could have unwanted behaviour with the openFromSpace shortcut.
> 
> Is the `BlSpace>>root element` the same in Pyramid and in the Space we opened it from ? (We have 2 BlSpace and also 2 root BlElement. One from the original space, one to display the Pyramid Editor)

Hi @Nyan11!

We shouldn't show users the technical details of Pyramid. 
So, technically, it's good to handle two "Spaces": one for editing and one for viewing. 
We can improve this later if needed.

Why does it matter? 
From a user perspective, in the Playground, when I haven't selected elements, I use a Space and add elements to it. 
As a user, I don't know the technical details of Pyramid, and I don't want to. 
Pyramid users expect a Bloc API level in the Playground. 
When no elements are selected, I can access the "root" element of the BlSpace (without an "s" because this is a Pyramid technical stuff).

If I understand your explaination there is an issue because if we expose the root to the user, this is not the "view" root but the pyramid edition "root", right ? The risk is to install behavior on this root and lost it when the view is opened in a test window or when the editor is closed to go back the original edited view ?

2023-12-09 19:42 UTC, Nyan11 commented
> If I understand your explaination there is an issue because if we expose the root to the user, this is not the "view" root but the pyramid edition "root", right ? The risk is to install behavior on this root and lost it when the view is opened in a test window or when the editor is closed to go back the original edited view ?

Yes. For example, i set a specific layout in my root to display the children, this layout will not be replicated in "test space" or "original space".

2023-12-09 19:53 UTC, Nyan11 commented
One possible solution is to force the user to always have always one element as root.

The +++
* the root can be the same as the "original" root and the "test" root
* It make serializing/materializing a bit simplier.

The ---
* You cannot have multiples elements as roots
* It will change a lot of thing in Pyramid
* If you want to replace the root element, it will be complicated. (For example if you want your root to be a (ToPanel and not a BlElement)

2023-12-12 16:20 UTC, labordep requested changes

2023-12-12 16:20 UTC, labordep commented on src/Pyramid/PyramidSpCodeObjectInteractionModel.class.st
> +		^ 'roots (use #Collection methods)' ].
Change term "roots" to "first level elements"

2023-12-12 16:25 UTC, labordep requested changes

2023-12-12 16:25 UTC, labordep commented on src/Pyramid/PyramidSpCodeObjectInteractionModel.class.st
> +	self projectModel selection size = 1 ifTrue: [ ^ 'a single element' ].
"a single" -> "the selected"

2023-12-12 16:25 UTC, labordep commented on src/Pyramid/PyramidSpCodeObjectInteractionModel.class.st
> +	^ 'a collection of <1p> elements' expandMacrosWith:
"a collection of" -> "an Array of selected "

2023-12-12 16:48 UTC, Nyan11 commented
Chec this work : https://github.com/OpenSmock/Pyramid/issues/111

2023-12-14 09:16 UTC, Nyan11 commented
![image](https://github.com/OpenSmock/Pyramid/assets/34318678/6904f14d-fc12-44ed-85bb-f990415226b6)

![image](https://github.com/OpenSmock/Pyramid/assets/34318678/ade68df3-4628-47e6-b1da-74d5fa749576)

![image](https://github.com/OpenSmock/Pyramid/assets/34318678/4ea25d2e-a0e0-4c71-919b-a4f488db5ecf)

![image](https://github.com/OpenSmock/Pyramid/assets/34318678/53d36bed-c16c-486f-bc57-e2666c5be148)

![image](https://github.com/OpenSmock/Pyramid/assets/34318678/2dfa2628-e783-48f0-95a1-96054d9f5881)

2023-12-16 18:54 UTC, labordep approved these changes

2023-12-16 18:54 UTC, merged