Toplo with themes and skins
OpenSmock/Pyramid pull request #156
Opened 2024-02-01 17:27 UTC by Nyan11

Fix: #155

It is a PR to make Pyramid compatible with Toplo.

You need to validate the pull request on Bloc-Serialization at: https://github.com/OpenSmock/Bloc-Serialization/pull/14.

Attention when this version will be merged it will possibily break all projects that currently use Pyramid.

It change the serialization (all examples are brokens + all specials widget (switch and visibility).
It change deep mechanics inside Pyramid.

2024-02-01 17:34 UTC, Nyan11 commented
What's comming: 
![image](https://github.com/OpenSmock/Pyramid/assets/34318678/80c5036c-e01a-4797-a7de-ebea002f14fa)

2024-02-01 20:09 UTC, labordep commented
Thanks @Nyan11

> You need to validate the pull request on Bloc-Serialization at: [OpenSmock/Bloc-Serialization#14](https://github.com/OpenSmock/Bloc-Serialization/pull/14).

Ok, I have a review with comments.
 
> Attention when this version will be merged it will possibily break all projects that currently use Pyramid.

No problem this is an alpha version and this is normal to introduce problems between them.

2024-02-01 20:19 UTC, labordep reviewed
Comments + waiting for https://github.com/pharo-graphics/Toplo/pull/97

2024-02-01 20:19 UTC, labordep commented on src/BaselineOfPyramid/BaselineOfPyramid.class.st
Ok for this new baseline. 
I don't think this is usefull to have separate version because users have to use Toplo... however if we succeed to execute CI in these two baselines it is a good practice to have a better architecture.

2024-02-01 20:19 UTC, labordep commented on src/Pyramid-Bloc/PyramidPluginEditOnRunning.class.st
Haha, do you have the problem on your PC ? 
https://github.com/pharo-graphics/Bloc/issues/356

2024-03-08 13:31 UTC, labordep requested changes
Need to update CI scripts.

2024-03-08 13:31 UTC, labordep commented on src/BaselineOfPyramid/BaselineOfPyramid.class.st
> +	spec group: 'default' with: #( 'PyramidBloc' 'PyramidToplo' ). "complete version"
Rename PyramidBloc->Bloc and PyramidToplo-> Toplo

2024-03-08 13:43 UTC, labordep commented on src/BaselineOfPyramid/BaselineOfPyramid.class.st
> +	spec group: 'default' with: #( 'PyramidBloc' 'PyramidToplo' ). "complete version"
Oups seems not possible to do that :(

2024-03-08 13:58 UTC, labordep commented
@Nyan11 I think the example PyramidToploExamples>>buttons need to be recreate because there is an exception on opening. And this is strange because ToElement have serialized children :/

2024-03-08 13:58 UTC, Nyan11 commented
> @Nyan11 I think the example PyramidToploExamples>>buttons need to be recreate because there is an exception on opening. And this is strange because ToElement have serialized children :/

I will check it

2024-03-08 14:33 UTC, Nyan11 commented
We need to load the dev branch of Toplo but currently Toplo is bugged

2024-03-08 15:24 UTC, Nyan11 commented
@labordep Everything should work, but you need to merge first: https://github.com/OpenSmock/Toplo-Serialization/pull/1 and: https://github.com/pharo-graphics/Toplo/pull/123

2024-03-08 17:29 UTC, labordep commented
> @labordep Everything should work, but you need to merge first: [OpenSmock/Toplo-Serialization#1](https://github.com/OpenSmock/Toplo-Serialization/pull/1) and: [pharo-graphics/Toplo#123](https://github.com/pharo-graphics/Toplo/pull/123) . You should check on your side if everithing is ok before merging.
> 
> Toplo-Serialization -> If we have a ToElement, it should serialized itt's children. If we have anything with TToPlaceHolder trait it should serialize it's children. Everithing else should not serialize it's children.
> 
> Toplo -> There is a bug that make impossible to instanciate ToElement currently on master ... (it also break the tests of Toplo-Serialization)

Ok I can launch the example, but buttons are all the same:

![image](https://github.com/OpenSmock/Pyramid/assets/49183340/b244b2fc-050d-4397-91cc-7c9417242740)

2024-03-08 17:40 UTC, Nyan11 commented
Do you have this ?

![image](https://github.com/OpenSmock/Pyramid/assets/34318678/aca34849-a7e7-46bc-97cd-4917e0663f90)

It is a menu to select the theme

2024-03-08 17:44 UTC, labordep commented
> Do you have this ?
> 
> ![image](https://private-user-images.githubusercontent.com/34318678/311316789-aca34849-a7e7-46bc-97cd-4917e0663f90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MTk5MDcsIm5iZiI6MTcwOTkxOTYwNywicGF0aCI6Ii8zNDMxODY3OC8zMTEzMTY3ODktYWNhMzQ4NDktYTdlNy00NmJjLTk3Y2QtNDkxN2UwNjYzZjkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDE3NDAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkNzdlMTQ0ZmM1M2RiY2IyNTNjMDY1NTk3MjhmYWYyZTljY2Y3YWQ3Y2Y2OWIxMzcyMzNlMTVkZjhlOWIxOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bbhVM7zwgfE8GnQIEcHVf4XnLKoXruao_4jqS3UaILA)
> 
> It is a menu to select the theme

Yes good!
But when I save and re-edit the theme that I choose is not recovered. Is it normal?

2024-03-08 17:55 UTC, Nyan11 commented
Yes i did not implement a way to save the default theme for the space.

2024-03-08 17:56 UTC, Nyan11 commented
It is complicated, since we only save the BlElement inside the space and not directly the space ...

2024-03-08 17:57 UTC, labordep commented
> It is complicated, since it only saves the BlElements inside the space and not directly the space ...

Ok thanks @Nyan11, we will discuss on that later.

2024-03-08 17:58 UTC, merged